apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppingapi-deployment
  labels:
    app: shoppingapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shoppingapi
  template:
    metadata:
      labels:
        app: shoppingapi
    spec:
      containers:
        - name: shoppingapi
          image: shoppingacrtws.azurecr.io/shoppingapi:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: DatabaseSettings__ConnectionString
              valueFrom:
                configMapKeyRef:
                  name: mongo-configmap
                  key: connectionstring
          resources:
            requests:
              memory: "64Mi"
              cpu: 250m
            limits:
              memory: "120Mi"
              cpu: "500m"
      imagePullSecrets:
        - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: shoppingapi-service
spec:
  selector:
    app: shoppingapi
  ports:
    - port: 80
      targetPort: 5002 #pod listen in the container