# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  shoppingclient:
    image: shoppingclient
    build:
      context: .
      dockerfile: Shopping/Shopping.Client/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5001:5001
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
