# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - Shopping/Shopping.Client/*
    - aks/shopping-client.yaml

resources:
- repo: self

variables:

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '02723187-1fe9-4adc-9d70-d069e70afa58'
  imageRepository: 'shoppingclient'
  containerRegistry: 'shoppingacrtws.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Shopping/Shopping.Client/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'shoppingacrtws1911c556-auth'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'


stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool: Default
    steps:
    - task: Docker@2
      displayName: login to ACR
      inputs: 
        command: login
        containerRegistry: $(dockerRegistryServiceConnection)

    # Build docker Image using docker buildx
    - script: |
        docker run --privileged --rm tonistiigi/binfmt --install all
        docker buildx create --use
        docker buildx build \
          --platform linux/amd64 \
          -t $(containerRegistry)/$(imageRepository):$(tag) \
          -f $(dockerfilePath) \
          $(Build.SourcesDirectory) \
          --push 
      displayName: Build and Push image to container registry

    - publish: aks
      artifact: aks

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build

  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool: Default
    environment: 'wslearnrundevops.default'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: createSecret
              secretName: $(imagePullSecret)
              dockerRegistryEndpoint: $(dockerRegistryServiceConnection)

          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              manifests: |
                $(Pipeline.Workspace)/aks/shopping-client.yaml
                $(Pipeline.Workspace)/aks/shopping-autoscale.yaml
              imagePullSecrets: |
                $(imagePullSecret)
              containers: |
                $(containerRegistry)/$(imageRepository):$(tag)

